repos:
- repo: local
  hooks:
    - id: system
      name: black
      entry: poetry run black
      language: system
      types: [python]
    - id: system
      name: isort
      entry: poetry run isort
      language: system
      types: [python]
    - id: system
      name: flake8
      entry: poetry run flake8 --ignore=E731
      language: system
      types: [python]
    - id: system
      name: pytest
      entry: poetry run pytest
      language: system
      types: [python]
      pass_filenames: false